os:
    - linux
    - osx

language: java

jdk:
    - oraclejdk8
    - openjdk9
    - openjdk11

env:
    - GRAALVM_VERSION="1.0.0-rc13"
    - GRAALVM_VERSION="NONE" SL_BUILD_NATIVE="false"

matrix:
    exclude:
        - env: GRAALVM_VERSION="1.0.0-rc13"
          jdk: openjdk11
        - jdk: openjdk9
          os: linux
        - jdk: oraclejdk8
          os: osx

install:
    - |
        cd .. && mv simplelanguage "simple language" && cd "simple language"
        if [[ "$GRAALVM_VERSION" != "NONE" ]]; then
          if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then DOWNLOAD_OS_NAME="macos"; fi
          if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then DOWNLOAD_OS_NAME="linux"; fi
          curl -LJ "https://github.com/oracle/graal/releases/download/vm-$GRAALVM_VERSION/graalvm-ce-$GRAALVM_VERSION-$DOWNLOAD_OS_NAME-amd64.tar.gz" --output graalvm.tar.gz
          tar -xzf graalvm.tar.gz
          export JAVA_HOME="$(pwd)/graalvm-ce-$GRAALVM_VERSION"
          if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export JAVA_HOME="$JAVA_HOME/Contents/Home"; fi
        else
          if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
        fi

script:
    - mvn package
    - ./sl language/tests/Add.sl
    - if [[ "$GRAALVM_VERSION" != "NONE" ]]; then ./native/slnative language/tests/Add.sl; fi
    - if [[ "$GRAALVM_VERSION" != "NONE" ]]; then "$JAVA_HOME/bin/gu" install -F component/sl-component.jar ; fi
    - if [[ "$GRAALVM_VERSION" != "NONE" ]]; then "$JAVA_HOME/bin/sl" language/tests/Add.sl; fi
    - if [[ "$GRAALVM_VERSION" != "NONE" ]]; then "$JAVA_HOME/bin/slnative" language/tests/Add.sl; fi
    - if [[ "$GRAALVM_VERSION" != "NONE" ]]; then "$JAVA_HOME/bin/polyglot" --jvm --language sl --file language/tests/Add.sl; fi
    - ./generate_parser
    - mvn package
    - ./sl language/tests/Add.sl
